'''
Created on 2024-05-22

@author: dnikolic
'''

def provide_failure_messaage():
    assert False, "This is the message that explains the failure"

provide_failure_messaage()
